# Data Preprocessing | IBM SkillsBuild Internship

## Import the required libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## Import the dataset

In [2]:
dataset = pd.read_csv('Data.csv')
x = dataset.iloc[: , :-1].values #iloc is where my x is locating
y = dataset.iloc[:, -1].values

In [4]:
print(x) #replace the nan either the mean or median

[['India' 44.0 72000.0]
 ['Thailand ' 27.0 48000.0]
 ['Indonesia' 30.0 54000.0]
 ['China' 38.0 61000.0]
 ['India' 40.0 nan]
 ['China' 35.0 58000.0]
 ['Thailand ' nan 52000.0]
 ['India' 48.0 79000.0]
 ['Indonesia' 50.0 83000.0]
 ['Thailand ' 37.0 67000.0]
 ['India' 25.0 nan]
 ['Thailand ' 36.0 60000.0]
 ['Indonesia' 42.0 64000.0]
 ['India' nan 40000.0]
 ['Thailand ' 52.0 90000.0]
 ['Indonesia' nan 55000.0]
 ['China' 41.0 nan]
 ['India' 29.0 48000.0]
 ['China' 43.0 70000.0]]


In [5]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes' 'No' 'No' 'Yes'
 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


## Solving for missing data

In [9]:
#use simpleimputer it is a Univariate imputer for completing missing values with simple strategies.
#Replace missing values using a descriptive statistic (e.g. mean, median, or most frequent) along each column, or using a constant value.
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values = np.nan, strategy = 'mean') #here we use numpy for array
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[: , 1:3])

In [10]:
print(x)

[['India' 44.0 72000.0]
 ['Thailand ' 27.0 48000.0]
 ['Indonesia' 30.0 54000.0]
 ['China' 38.0 61000.0]
 ['India' 40.0 62562.5]
 ['China' 35.0 58000.0]
 ['Thailand ' 38.5625 52000.0]
 ['India' 48.0 79000.0]
 ['Indonesia' 50.0 83000.0]
 ['Thailand ' 37.0 67000.0]
 ['India' 25.0 62562.5]
 ['Thailand ' 36.0 60000.0]
 ['Indonesia' 42.0 64000.0]
 ['India' 38.5625 40000.0]
 ['Thailand ' 52.0 90000.0]
 ['Indonesia' 38.5625 55000.0]
 ['China' 41.0 62562.5]
 ['India' 29.0 48000.0]
 ['China' 43.0 70000.0]]


## Encoding categorical data

In [11]:
from sklearn.compose import make_column_transformer
from sklearn.preprocessing import OneHotEncoder
ct = make_column_transformer((OneHotEncoder(), [0]), remainder ='passthrough')
x = np.array(ct.fit_transform(x))

In [12]:
print(x)

[[0.0 1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 0.0 1.0 27.0 48000.0]
 [0.0 0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 0.0 38.0 61000.0]
 [0.0 1.0 0.0 0.0 40.0 62562.5]
 [1.0 0.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 0.0 1.0 38.5625 52000.0]
 [0.0 1.0 0.0 0.0 48.0 79000.0]
 [0.0 0.0 1.0 0.0 50.0 83000.0]
 [0.0 0.0 0.0 1.0 37.0 67000.0]
 [0.0 1.0 0.0 0.0 25.0 62562.5]
 [0.0 0.0 0.0 1.0 36.0 60000.0]
 [0.0 0.0 1.0 0.0 42.0 64000.0]
 [0.0 1.0 0.0 0.0 38.5625 40000.0]
 [0.0 0.0 0.0 1.0 52.0 90000.0]
 [0.0 0.0 1.0 0.0 38.5625 55000.0]
 [1.0 0.0 0.0 0.0 41.0 62562.5]
 [0.0 1.0 0.0 0.0 29.0 48000.0]
 [1.0 0.0 0.0 0.0 43.0 70000.0]]


### Encoding the Independent Variable

### Encoding the Dependent Variable

In [13]:
from sklearn.preprocessing import LabelEncoder #it already returns an array
le= LabelEncoder()
y = le.fit_transform(y)


In [14]:
print(y)

[0 1 0 0 1 1 0 1 0 1 0 0 1 1 1 0 1 0 1]


## Splitting the dataset into the Training set and Test set

In [15]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=1)

In [16]:
print(x_test)

[[1.0 0.0 0.0 0.0 38.0 61000.0]
 [0.0 0.0 1.0 0.0 38.5625 55000.0]
 [0.0 0.0 0.0 1.0 38.5625 52000.0]
 [0.0 1.0 0.0 0.0 25.0 62562.5]]


## Feature Scaling

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [17]:
print(x_train)

[[0.0 0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 0.0 1.0 52.0 90000.0]
 [0.0 1.0 0.0 0.0 40.0 62562.5]
 [1.0 0.0 0.0 0.0 41.0 62562.5]
 [0.0 1.0 0.0 0.0 48.0 79000.0]
 [0.0 0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 0.0 38.5625 40000.0]
 [0.0 1.0 0.0 0.0 44.0 72000.0]
 [1.0 0.0 0.0 0.0 43.0 70000.0]
 [0.0 1.0 0.0 0.0 29.0 48000.0]
 [0.0 0.0 0.0 1.0 37.0 67000.0]
 [0.0 0.0 1.0 0.0 50.0 83000.0]
 [0.0 0.0 1.0 0.0 42.0 64000.0]
 [0.0 0.0 0.0 1.0 36.0 60000.0]
 [1.0 0.0 0.0 0.0 35.0 58000.0]]


In [18]:
print(x_train)
print(x_test)

[[0.0 0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 0.0 1.0 52.0 90000.0]
 [0.0 1.0 0.0 0.0 40.0 62562.5]
 [1.0 0.0 0.0 0.0 41.0 62562.5]
 [0.0 1.0 0.0 0.0 48.0 79000.0]
 [0.0 0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 0.0 38.5625 40000.0]
 [0.0 1.0 0.0 0.0 44.0 72000.0]
 [1.0 0.0 0.0 0.0 43.0 70000.0]
 [0.0 1.0 0.0 0.0 29.0 48000.0]
 [0.0 0.0 0.0 1.0 37.0 67000.0]
 [0.0 0.0 1.0 0.0 50.0 83000.0]
 [0.0 0.0 1.0 0.0 42.0 64000.0]
 [0.0 0.0 0.0 1.0 36.0 60000.0]
 [1.0 0.0 0.0 0.0 35.0 58000.0]]
[[1.0 0.0 0.0 0.0 38.0 61000.0]
 [0.0 0.0 1.0 0.0 38.5625 55000.0]
 [0.0 0.0 0.0 1.0 38.5625 52000.0]
 [0.0 1.0 0.0 0.0 25.0 62562.5]]
